user1 = User.create(email: "1@gmail.com", password: "1")
user2 = User.create(email: "2@gmail.com", password: "2")
user3 = User.create(email: "3@gmail.com", password: "3")
user4 = User.create(email: "4@gmail.com", password: "4")
user5 = User.create(email: "bombo@gmail.com", password: "b")

deck1 = Deck.create(name: "Geografía")
deck2 = Deck.create(name: "Historia")
deck3 = Deck.create(name: "Futbol")
#Sólo quitar comentarios de game para hacer las pruebas de las relaciones en consola
# game1 = Game.create(user_id: user1.id, deck_id: deck1.id)
# game2 = Game.create(user_id: user2.id, deck_id: deck2.id)
# game3 = Game.create(user_id: user3.id, deck_id: deck3.id)

question1 = Question.create(question: "¿En qué estado de la República se encuentra la ciudad de Guadalajara?", deck_id: deck1.id)
question2 = Question.create(question: "¿Los Grandes Lagos se encuentran en el continente:?", deck_id: deck1.id)
question3 = Question.create(question: "¿Planeta mas pequeño?", deck_id: deck1.id)
question4 = Question.create(question: "¿Es la representación mas adecuada de la tierra?", deck_id: deck1.id)
question5 = Question.create(question: "¿El océano más grande y más profundo?", deck_id: deck1.id)
question6 = Question.create(question: "¿Evento con el que inicia la segunda Guerra Mundial?", deck_id: deck2.id)
question7 = Question.create(question: "¿Año en que inicia la segunda guerra mundial?", deck_id: deck2.id)
question8 = Question.create(question: "¿Presidente de la URSS durante la segunda guerra mundial?", deck_id: deck2.id)
question9 = Question.create(question: "¿En dónde se encuentran las pirámides del Sol y la Luna?", deck_id: deck2.id)
question10 = Question.create(question: "¿Fecha en la que se celebra la Independencia de México?", deck_id: deck2.id)
question11 = Question.create(question: "¿En donde fue el primer mundial?", deck_id: deck3.id)
question12 = Question.create(question: "¿Cual fue el equipo que gano el primer mundial?", deck_id: deck3.id)
question13 = Question.create(question: "¿Cual es el equipo que a ganado mas mundiales?", deck_id: deck3.id)
question14 = Question.create(question: "¿Quien es el mejor futbolista?", deck_id: deck3.id)
question15 = Question.create(question: "¿¿Quien es el mejor futbolista maxicano de la historia?", deck_id: deck3.id)

option_question1  = Option.create(question_id: question1.id, option: "chicago", answer: false)
option_question2  = Option.create(question_id: question1.id, option: "df", answer: false)
option_question3  = Option.create(question_id: question1.id, option: "Jalisco", answer: true)
option_question4  = Option.create(question_id: question2.id, option: "Oceanía", answer: false)
option_question5  = Option.create(question_id: question2.id, option: "Europa", answer: false)
option_question6  = Option.create(question_id: question2.id, option: "América", answer: true)
option_question7  = Option.create(question_id: question3.id, option: "Júpiter", answer: false)
option_question8  = Option.create(question_id: question3.id, option: "Urano", answer: false)
option_question9  = Option.create(question_id: question3.id, option: "Plutón", answer: true)
option_question10 = Option.create(question_id: question4.id, option: "Globo ovalo", answer: false)
option_question11 = Option.create(question_id: question4.id, option: "Globo espírical", answer: false)
option_question12 = Option.create(question_id: question4.id, option: "Globe terráqueo", answer: true)
option_question13 = Option.create(question_id: question5.id, option: "Atlantico", answer: false)
option_question14 = Option.create(question_id: question5.id, option: "Indico", answer: false)
option_question15 = Option.create(question_id: question5.id, option: "Pacífico", answer: true)

option_question16 = Option.create(question_id: question6.id, option: "Invasión de Alemania a URSS", answer: false)
option_question17 = Option.create(question_id: question6.id, option: "Invasión de Polonia a Alemania", answer: false)
option_question18 = Option.create(question_id: question6.id, option: "Invasión de Alemania a Polonia", answer: true)
option_question19 = Option.create(question_id: question7.id, option: "1999", answer: false)
option_question20 = Option.create(question_id: question7.id, option: "1993", answer: false)
option_question21 = Option.create(question_id: question7.id, option: "1939", answer: true)
option_question22 = Option.create(question_id: question8.id, option: "Roosevelt", answer: false)
option_question23 = Option.create(question_id: question8.id, option: "Churchill", answer: false)
option_question24 = Option.create(question_id: question8.id, option: "Stalin", answer: true)
option_question25 = Option.create(question_id: question9.id, option: "Monte Albán", answer: false)
option_question26 = Option.create(question_id: question9.id, option: "Cholula", answer: false)
option_question27 = Option.create(question_id: question9.id, option: "Teotihuacan", answer: true)
option_question28 = Option.create(question_id: question10.id, option: "15 de septiembre", answer: false)
option_question29 = Option.create(question_id: question10.id, option: "14 de septiembre", answer: false)
option_question30 = Option.create(question_id: question10.id, option: "16 de septiembre", answer: true)

option_question31 = Option.create(question_id: question11.id, option: "Argentina", answer: false)
option_question32 = Option.create(question_id: question11.id, option: "Brasil", answer: false)
option_question33 = Option.create(question_id: question11.id, option: "Uruguay", answer: true)
option_question34 = Option.create(question_id: question12.id, option: "Brasil", answer: false)
option_question35 = Option.create(question_id: question12.id, option: "México", answer: false)
option_question36 = Option.create(question_id: question12.id, option: "Uruguay ", answer: true)
option_question37 = Option.create(question_id: question13.id, option: "Panama", answer: false)
option_question38 = Option.create(question_id: question13.id, option: "Argentina", answer: false)
option_question39 = Option.create(question_id: question13.id, option: "Brasil", answer: true)
option_question40 = Option.create(question_id: question14.id, option: "Cristiano Ronaldo", answer: false)
option_question41 = Option.create(question_id: question14.id, option: "Ronaldiño", answer: false)
option_question42 = Option.create(question_id: question14.id, option: "Messi", answer: true)
option_question43 = Option.create(question_id: question15.id, option: "Rafa Márquez", answer: false)
option_question44 = Option.create(question_id: question15.id, option: "Cuauhtémoc Blanco", answer: false)
option_question45 = Option.create(question_id: question15.id, option: "Hugo Sanchez", answer: true)

#Sólo quitar comentarios de game para hacer las pruebas de las relaciones en consola
# answer_games1 = AnswerGame.create(game_id: game1.id, question_id: question1.id, user_answer: option_question3.id, score: 1)
# answer_games2 = AnswerGame.create(game_id: game2.id, question_id: question2.id, user_answer: option_question3.id, score: 0)
# answer_games3 = AnswerGame.create(game_id: game3.id, question_id: question3.id, user_answer: option_question3.id, score: 0)
